### ISSUE TITLE
Cell.setImage_ makes an XHR request for SVG images every time

### ISSUE THREAD

**Issue by RossBrunton** [amishne/mipui#100]
If setImage_ is given an SVG URI, it downloads the file using XHR every time, rather than using a (JS) cached version.

This means, for example, while dragging the cursor across the map with the token tool it makes tons of requests. If these requests take a while (or time out), you have a lot of requests waiting to be processed, which results in a lot of CPU usage. Even when they pulled from the browser cache, there is a noticeable delay on the "preview" appearing on the map.

**Comment by amishne** [comment]
I agree it's really wasteful and slow, I'll fix it - thanks for drawing my attention to this!
But I'm not considering this high priority because it's just one of many awful stuff in my code and at least the user-visible impact here, while noticeable, doesn't seem that terrible.
