### ISSUE TITLE
Ensure default export size is roll20-friendly

### ISSUE THREAD

**Issue by amishne** [amishne/mipui#121]

**Comment by amishne** [comment]
A helpful 4chan user writes:
![roll20_problem](https://user-images.githubusercontent.com/3197814/33048342-59742a6e-ce28-11e7-8f43-a0bdcedfcd40.png)

**Comment by Expletive** [comment]
When I exported [this map](https://www.mipui.net:/app/index.html?mid=mnbf9xjr7uj) I found that the top and left edges are each 10 pixels too far the grid, and the bottom and right edges are similarly wrong by 7 pixels.
