### ISSUE TITLE
endcell not properly removed when resizing and then undoing the resize

### ISSUE THREAD

**Issue by freakinhippie** [amishne/mipui#153]
I've received the error above while building a map. It seems that the map is incomplete and that error is triggering an exception in Firebase. Once it is triggered, the cloud sync seems to stop functioning entirely.

I attempted to fork the map in the hopes that it would resolve the issue. The fork succeeded, but the map still seems to have some corruption. This is the original map, and the forked version as well:

[Original Map](https://www.mipui.net/app/index.html?mid=m1uwqllpje1)
[Forked Map](https://www.mipui.net/app/index.html?mid=m1u7vcobq9s)

I'm not certain if this is the cause, but I'll try to explain what I'd done prior to the error manifesting.

I was trying to reduce the viewable area of the map by using the arrows at the bottom to subtract one row at a time. Since I wasn't sure if that was the proper way of reducing the viewing area without destroying the content, I only subtracted one row, then I readded it to see if the content was still there. The content was gone so I used the undo function a few times to return to the previous state. That seemed to succeed but afterward when I tried to reload the map I got the Firebase warning and exception.

Is there any way to extract the map data to inspect it? I would prefer to not have to recreate it entirely.

[www.mipui.net-1517766894465.log](https://github.com/amishne/mipui/files/1693142/www.mipui.net-1517766894465.log)

**Comment by amishne** [comment]
Thanks for the bug report and sorry about the inconvenience! The root cause seems to be related to improperly restoring the map size during the undo operation. I'll take a look into it.

Meanwhile, I manually fixed the problem and prepared a functional copy at https://www.mipui.net/app/index.html?mid=muyr55k9vgv - you can fork it to get an editable copy and then continue your work. Let me know if anything's still broken there.

**Comment by freakinhippie** [comment]
Wow, you rock! Thank you!

**Comment by amishne** [comment]
Can no longer reproduce in current version, shelving for now.
