### ISSUE TITLE
Add ascending / descending variations to stairs

### ISSUE THREAD

**Issue by amishne** [amishne/mipui#57]
This means two kinds of horizontal stairs and two kinds of vertical stairs, which doesn't sound so bad.

**Comment by amir-arad** [comment]
for a clasic look I'd go with:

http://cf.geekdo-images.com/images/pic1008026.png

**Comment by amishne** [comment]
That image is one of my main inspirations!
But I might end up having different default appearance, depending on how it looks in practice. This will be controllable by themes, though.

**Comment by amishne** [comment]
Fixed in staging.
