### ISSUE TITLE
Request - "locked" doors and "diagonal" separators (doors, windows, etc...)

### ISSUE THREAD

**Issue by PalaNolho** [amishne/mipui#99]
1- I would like to request if you could add some locked door separators (like a dor but with a black dot in the centre).

2- I also would like to request if you could add some diagonal separators (like doors, windows, etc..) since, otherwise, it's not possible to add such things to diagonal not "round" walls

Many thanks in advance

**Comment by PalaNolho** [comment]
1) seems to be a duplicate of #55 
2) seems to be duplicated with #85

**Comment by amishne** [comment]
Thanks for the feedback!
And yes both of these are on my todo list, as part of a larger separator overhaul. Closing this issue meanwhile as a dup, but I'll keep it in mind when I think about prioritizing tasks.
